sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-ntp-client-image .
  # disable rvm, use system Ruby
  - rvm reset
  # install newer augeasget repo with newer augeas, otherwise ruby-augeas fails (see https://github.com/yast/yast-network/pull/454#issuecomment-253795507)
  - sudo add-apt-repository -y ppa:raphink/augeas
  - sudo apt-get update
  - sudo apt-get install libaugeas-dev libxml2-dev
  # end of augeas install
  - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
  - sh ./travis_setup.sh -p "rake yast2-devtools yast2 rake yast2-country-data libaugeas-dev" -g "yast-rake gettext yard rspec:3.3.0 simplecov coveralls rubocop:0.29.1 cfa"
script:
  # the "yast-travis-ruby" script is included in the base yastdevel/ruby image
  # see https://github.com/yast/docker-yast-ruby/blob/master/yast-travis-ruby
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast-ntp-client-image yast-travis-ruby
