language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools yast2-testsuite yast2 yast2-country-data" -g "yast-rake gettext simplecov coveralls rubocop:0.29.1"
script:
    - rake check:syntax
    - rake check:pot
    - rubocop
    - yardoc
    - COVERAGE=1 rake test:unit
    - sudo rake install

